// Builds trimmed icon stylesheets that keep only the icons this site actually uses.
//
//   node tools/subset-icons.mjs
//
// Re-run it whenever you add a new icon class (mdi-*, linearicons-*, fa-*) to any page or script,
// otherwise the new icon renders as an empty box. The original stylesheets are never modified.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const TARGETS = [
  { src: 'css/fonts.css', out: 'css/fonts.subset.css' },
  { src: 'css/fontawesome-6.4.0-all.min.css', out: 'css/fontawesome-6.4.0.subset.min.css' },
];

// Everywhere an icon class can come from: pages + all scripts (incl. vendor bundles).
function walk(dir, ext) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return walk(p, ext);
    return e.name.endsWith(ext) ? [p] : [];
  });
}
const sources = [
  ...fs.readdirSync(root).filter((f) => f.endsWith('.html')).map((f) => path.join(root, f)),
  ...walk(path.join(root, 'js'), '.js'),
  ...walk(path.join(root, 'campaign-widgets'), '.js'),
];

const ICON_CLASS = /\b(?:mdi|linearicons|fl-bigmug-line|fa)-[a-z0-9-]+/g;
const used = new Set();
for (const file of sources) {
  for (const m of fs.readFileSync(file, 'utf8').match(ICON_CLASS) ?? []) used.add(m);
}

// Split CSS into top-level blocks, respecting nested braces (@media, @keyframes) and strings.
function topLevelBlocks(css) {
  const blocks = [];
  let depth = 0, start = 0, quote = null;
  for (let i = 0; i < css.length; i++) {
    const c = css[i];
    if (quote) { if (c === '\\') i++; else if (c === quote) quote = null; continue; }
    if (c === '"' || c === "'") quote = c;
    else if (c === '{') depth++;
    else if (c === '}' && --depth === 0) { blocks.push(css.slice(start, i + 1).trim()); start = i + 1; }
  }
  return blocks;
}

// A "glyph rule" is `.prefix-name:before` — the part that makes up the bulk of these files.
const GLYPH_SELECTOR = /^\.((?:mdi|linearicons|fl-bigmug-line|fa)-[a-z0-9-]+)::?before$/;

for (const { src, out } of TARGETS) {
  const input = fs.readFileSync(path.join(root, src), 'utf8');
  const licenses = input.match(/\/\*![\s\S]*?\*\//g) ?? [];
  const css = input.replace(/\/\*[\s\S]*?\*\//g, '');

  const kept = [];
  let dropped = 0;
  for (const block of topLevelBlocks(css)) {
    if (block.startsWith('@')) { kept.push(block); continue; }
    const brace = block.indexOf('{');
    const selectors = block.slice(0, brace).split(',').map((s) => s.trim());
    const keep = selectors.filter((s) => {
      const glyph = s.match(GLYPH_SELECTOR);
      return !glyph || used.has(glyph[1]);
    });
    if (keep.length === 0) { dropped++; continue; }
    kept.push(keep.join(',') + block.slice(brace));
  }

  const result = [...licenses, `/* Generated by tools/subset-icons.mjs from ${src}. Do not edit by hand. */`, ...kept].join('\n');
  fs.writeFileSync(path.join(root, out), result + '\n');
  console.log(`${src}: ${input.length} -> ${result.length} bytes (${dropped} unused icon rules removed) -> ${out}`);
}
console.log(`Icon classes found in use: ${[...used].sort().join(' ')}`);
